# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20170223_1039'),
        ('products', '0003_auto_20170223_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
